<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="generateNewPartID" Id="{2ba8f970-9107-400e-b5fd-be58bd38d569}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION generateNewPartID : STRING
VAR_INPUT
END_VAR
VAR
	GetTime			: GETSYSTEMTIME;
	fileTime		: T_filetime;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[	GetTime(timeLoDW=> fileTime.dwLowDateTime, timeHiDW=> filetime.dwHighDateTime);
	generateNewPartID		:= SYSTEMTIME_TO_STRING( FILETIME_TO_SYSTEMTIME(fileTime));]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>